import { MedicalCertificate, Patient, DoctorProfile } from '@/services/db';

interface CertificatePrintProps {
  certificate: MedicalCertificate;
  patient: Patient | undefined;
  doctor: DoctorProfile;
}

export function CertificatePrintTemplate({ certificate, patient, doctor }: CertificatePrintProps) {
  const age = patient ? new Date().getFullYear() - new Date(patient.dob).getFullYear() : 'N/A';

  return (
    <div className="print-page mx-auto bg-white text-slate-900 font-sans shadow-lg">
      {/* Header */}
      <div className="border-b-4 border-sky-600 pb-4 mb-6">
        <div className="flex justify-between items-start">
          <div className="w-2/3">
            <div className="flex items-center gap-3 mb-2">
              <div className="w-12 h-12 bg-sky-600 rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-xl">MC</span>
              </div>
              <div>
                <h1 className="text-2xl font-bold text-slate-900">{doctor.clinicName}</h1>
                <p className="text-xs text-slate-600">{doctor.clinicAddress}</p>
                <p className="text-xs text-slate-600">Phone: {doctor.phone} | Email: {doctor.email}</p>
              </div>
            </div>
          </div>
          <div className="text-right w-1/3">
            <h2 className="text-lg font-bold text-slate-800">{doctor.name}</h2>
            <p className="text-xs text-slate-600">{doctor.specialization}</p>
            <p className="text-xs text-slate-600 font-semibold">Reg: {doctor.regNumber}</p>
          </div>
        </div>
      </div>

      {/* Document Title */}
      <div className="text-center mb-8">
        <h2 className="text-4xl font-serif font-black uppercase tracking-widest text-slate-900">
          Medical Certificate
        </h2>
        <div className="w-32 h-1 bg-sky-600 mx-auto mt-2"></div>
      </div>

      {/* Certificate Body */}
      <div className="px-8 py-6 mb-8">
        <div className="text-base leading-relaxed text-slate-800 space-y-4">
          <p className="text-justify">
            This is to certify that I have professionally examined{' '}
            <span className="font-bold text-slate-900">
              {patient ? `${patient.firstName} ${patient.lastName}` : 'Unknown Patient'}
            </span>,{' '}
            age <span className="font-bold text-slate-900">{age} years</span>, gender{' '}
            <span className="font-bold text-slate-900">{patient?.gender || 'N/A'}</span>, on date{' '}
            <span className="font-bold text-slate-900">{certificate.issueDate}</span>.
          </p>
          <p className="text-justify">
            In my clinical opinion, the patient is diagnosed with{' '}
            <span className="font-bold text-slate-900">{certificate.diagnosis}</span> and requires a rest
            period of{' '}
            <span className="font-bold text-slate-900">{certificate.restPeriod}</span> for recovery.
          </p>
          {certificate.doctorRemarks && (
            <div className="bg-slate-50 border-l-4 border-sky-500 p-3 mt-4">
              <p className="text-sm italic text-slate-700">
                <span className="font-semibold">Doctor's Remarks:</span> {certificate.doctorRemarks}
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Footer */}
      <div className="mt-auto pt-8 border-t-2 border-slate-200 px-8">
        <div className="flex justify-between items-end">
          <div className="text-xs text-slate-500 space-y-1">
            <p>
              <span className="font-semibold">Certificate ID:</span> {certificate.id}
            </p>
            <p>
              <span className="font-semibold">Issue Date:</span> {certificate.issueDate}
            </p>
            <p>
              <span className="font-semibold">Patient ID:</span> {certificate.patientId}
            </p>
          </div>
          <div className="text-center w-48">
            {doctor.signature ? (
              <img src={doctor.signature} alt="Signature" className="h-12 mx-auto object-contain mb-1" />
            ) : (
              <div className="h-12 border-b-2 border-slate-300 mb-1"></div>
            )}
            <p className="text-sm font-bold text-slate-800 border-t border-slate-300 pt-1">{doctor.name}</p>
            <p className="text-xs text-slate-600">Registered Medical Officer</p>
          </div>
        </div>
      </div>

      {/* Watermark */}
      <div className="fixed bottom-4 right-4 text-xs text-slate-400">
        Generated by MediCare EMR System
      </div>
    </div>
  );
}
